name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_PUBLIC_KEY: ${{ secrets.CLIENT_PUBLIC_KEY }}
